jobs:
  buildOnLinux:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: ayltai/setup-graalvm@v1
      with:
        graalvm-version: 21.3.0
        java-version: 11
        native-image: true
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B clean package -Pnative --file pom.xml
    - continue-on-error: true
      name: Copy artifacts
      run: mkdir -p staging && cp target/log4j2-scanner staging/log4j2-scanner-linux-amd64
        && cp target/*.jar staging
    - continue-on-error: true
      name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: staging/
    - continue-on-error: true
      name: Clean staging
      run: rm -fr staging
  buildOnMacOS:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: ayltai/setup-graalvm@v1
      with:
        graalvm-version: 21.3.0
        java-version: 11
        native-image: true
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B clean package -Pnative --file pom.xml
    - continue-on-error: true
      name: Copy artifacts
      run: mkdir -p staging && cp target/log4j2-scanner staging/log4j2-scanner-mac-amd64
    - continue-on-error: true
      name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: staging
    - continue-on-error: true
      name: Clean staging
      run: rm -fr staging
  buildOnWindows:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: ilammy/msvc-dev-cmd@v1.5.0
    - continue-on-error: true
      uses: microsoft/setup-msbuild@v1
    - continue-on-error: true
      uses: ayltai/setup-graalvm@v1
      with:
        graalvm-version: 21.3.0
        java-version: 11
        native-image: true
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B clean package -Pnative --file pom.xml
      shell: powershell
    - continue-on-error: true
      name: Copy artifacts
      run: cp target/log4j2-scanner.exe log4j2-scanner-win-amd64.exe
    - continue-on-error: true
      name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: warn
        name: package
        path: target/*.exe
name: GraalVM native-image build
on:
  repository_dispatch:
    types: trigger-ga___graalVM.yml
