jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        architecture: x64
        distribution: temurin
        java-version: ${{ matrix.version }}
    - continue-on-error: true
      if: ${{ env.ACT }}
      name: Download Maven
      run: 'curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip
        -o maven.zip

        apt-get -y install unzip

        unzip -d /usr/share maven.zip

        rm maven.zip

        ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn

        echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment

        '
    - continue-on-error: true
      name: Build with Maven
      run: mvn -e --batch-mode --update-snapshots verify
    strategy:
      fail-fast: true
      matrix:
        version:
        - '8'
        - '17'
name: Java Build CI
on:
  repository_dispatch:
    types: trigger-ga___java-build.yaml
